[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tungstenite = "0.28.0"
ureq = "3.1.2"
whoami = "1.6.1"
